apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmoa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmoa
  template:
    metadata:
      labels:
        app: bookmoa
    spec:
      containers:
      - name: bookmoa
        image: asia-northeast3-docker.pkg.dev/<PROJECT-ID>/bookmoa/bookmoa:latest
        ports:
        - containerPort: 3000

        env:
        - name: DB_HOST
          value: "34.50.41.0"   
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "bookmoa"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_NAME
          value: "bookmoa"